"""
Script to generate vectors for each of the the words in eng and inuk dataset
[eng/inuk]_word2id.pkl -- generated by running create_bag_of_sentences.py

The two matrices W & b are generated by running run.py
"""
import numpy as np
import pickle

eng_words = pickle.load(open('./data/eng_word2id.pkl', 'rb'))
inuk_words = pickle.load(open('./data/inuk_word2id.pkl', 'rb'))

print len(eng_words)
print len(inuk_words)

b = np.load("results/bfinal.npy")
W = np.load("results/wfinal.npy")
W = W + np.expand_dims(b, -1)
eng_vectors = dict()
inuk_vectors = dict()
import ipdb; ipdb.set_trace()
with open('word2vec/eng.txt', 'w') as f:
    for (k, v) in eng_words.items():
        f.write(k + " " + " ".join([str(x) for x in W[v]])+"\n")

with open('word2vec/inuk.txt', 'w') as f:
    for (k, v) in inuk_words.items():
        f.write(k + " " + " ".join([str(x) for x in W[v]])+"\n")
